## Library `numpy`

##### Answer 1-1-1

In [1]:
import numpy as np

X = np.array([
    [[1, 2, 3, 4], [2, 3, 4, 5]],
    [[3, 4, 5, 6], [4, 5, 6, 7]],
    [[5, 6, 7, 8], [6, 7, 8, 9]]   
])
X

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [4, 5, 6, 7]],

       [[5, 6, 7, 8],
        [6, 7, 8, 9]]])

In [2]:
X.shape

(3, 2, 4)

In [3]:
X.size

24

##### Answer 1-1-2

In [4]:
rng = np.random.default_rng(42)
data = rng.normal(size=(10, 5)) / 2 + 5
data

array([[5.15235854, 4.48000795, 5.3752256 , 5.47028236, 4.02448241],
       [4.34891025, 5.0639202 , 4.8418787 , 4.99159942, 4.57347804],
       [5.43969899, 5.38889597, 5.03301535, 5.5636206 , 5.23375467],
       [4.57035377, 5.18437539, 4.5205587 , 5.43922515, 4.97503704],
       [4.90756882, 4.65953523, 5.61127067, 4.92273526, 4.78583609],
       [4.82393322, 5.26615459, 5.18272203, 5.20636631, 5.2154105 ],
       [6.0708238 , 4.79679249, 4.74387864, 4.59311364, 5.30798971],
       [5.56448615, 4.94302627, 4.57992176, 4.58775939, 5.32529639],
       [5.37162709, 5.27157713, 4.66724515, 5.11608066, 5.0583429 ],
       [5.1093443 , 5.43571439, 5.11179777, 5.33945678, 5.03378953]])

##### Answer 1-1-3

In [5]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [6]:
A[A[:, 0]>10, 0:2]

array([[20, 21],
       [30, 31],
       [40, 41]])

In [7]:
A[:, A[0, :]>2]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])

##### Answer 1-1-4

In [8]:
data = np.loadtxt('../data/stockholm.csv', delimiter=",", skiprows=1)
data[(data[:, 0] == 1817) * (data[:, 1] == 12) * (data[:, 2] == 5), :]

array([[1817. ,   12. ,    5. ,   -5.8]])

##### Answer 1-1-5

In [9]:
np.mean(data[(data[:, 1] == 1), 3])

-3.138255675029869

##### Answer 1-1-6

In [10]:
odkloni = [(np.std(data[(data[:, 1] == mesec), 3]), mesec) for mesec in range(1, 13)]
max(odkloni)

(5.15165648097469, 2)

##### Answer 1-1-7

In [11]:
povprečja = []
for leto in range(1800, 2012):
    for mesec in range(1, 13):
        t = np.mean(data[(data[:, 1] == mesec) * (data[:, 0] == leto), 3])
        povprečja.append((t, (leto, mesec)))
max(povprečja)

(21.53225806451613, (1994, 7))

##### Odgovor 1-1-8

##### Answer 1-1-8

In [12]:
years = np.unique(data[:, 0])[:-1].astype(int)
yearly_avg = np.array([data[data[:, 0] == year, 3].mean() for year in years])

In [13]:
[years[i] for i in range(1, len(years)) if yearly_avg[i-1] < yearly_avg[i]][-10:]

[2005, 2006, 2008, 2011, 2013, 2014, 2018, 2020, 2022, 2024]

##### Odgovor 1-1-9

##### Answer 1-1-9

In [14]:
t_leto = sorted(((t, leto) for leto, t in zip(years, yearly_avg)))
t_leto[-10:]

[(8.497814207650274, 2000),
 (8.533060109289618, 2008),
 (8.53945205479452, 2011),
 (8.586301369863014, 2019),
 (8.724931506849314, 2015),
 (8.817534246575342, 2022),
 (8.829589041095891, 2014),
 (8.881147540983607, 2024),
 (8.892054794520549, 2018),
 (9.75464480874317, 2020)]