## 1.1 Knjižnica `numpy`

##### Odgovor 1-1-1

In [1]:
import numpy as np

X = np.array([
    [[1, 2, 3, 4], [2, 3, 4, 5]],
    [[3, 4, 5, 6], [4, 5, 6, 7]],
    [[5, 6, 7, 8], [6, 7, 8, 9]]   
])
X

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [4, 5, 6, 7]],

       [[5, 6, 7, 8],
        [6, 7, 8, 9]]])

In [2]:
X.shape

(3, 2, 4)

In [3]:
X.size

24

##### Odgovor 1-1-2

In [4]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [5]:
A[A[:, 0]>10, 0:2]

array([[20, 21],
       [30, 31],
       [40, 41]])

In [6]:
A[:, A[0, :]>2]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])